---
kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
  name: metrics-generator-demo-1
  namespace: open-cluster-management-addon-observability
spec:
  replicas: 1
  selector:
    matchLabels:
      component: metrics-generator-demo-1
  template:
    metadata:
      labels:
        component: metrics-generator-demo-1
    spec:
      restartPolicy: Always
      serviceAccountName: endpoint-observability-operator-sa
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - name: metrics-generator-demo-1
          imagePullPolicy: Always
          image: davidmccarty/rhacm-metrics-generator
        - name: metrics-prometheus-demo-1
          imagePullPolicy: Always
          image: davidmccarty/metrics-prometheus
        - terminationMessagePath: /dev/termination-log
          name: metrics-scraper-demo-1
          command:
            - /usr/bin/telemeter-client
            - '--id=$(ID)'
            - '--from=$(FROM)'
            - '--to-upload=$(TO)'
            - '--interval=60s'
            - '--label="cluster=demo-1"'
            - '--label="clusterID=demo-1"'
            - '--label="clusterURL=demo-1.demo.com"'
            - '--limit-bytes=1073741824'
            - '--match={__name__="sample_counter"}'
            - '--match={__name__="sample_gauge"}'
            - '--match={__name__="sample_histogram_bucket"}'
            - '--match={__name__="sample_histogram_count"}'
            - '--match={__name__="sample_histogram_sum"}'
            - '--match={__name__="sample_summary"}'
            - '--match={__name__="sample_summary_count"}'
            - '--match={__name__="sample_summary_sum"}'
            - '--match={__name__="cluster_installer"}'
            - '--match={__name__="backup_snapshot_time"}'
            - '--match={__name__="up"}'
            - '--match={__name__="apiserver_request_duration_seconds_bucket"}'
            - '--match={__name__="apiserver_request_duration_seconds_count"}'
            - '--match={__name__="apiserver_request_duration_seconds_sum"}'
            - '--match={__name__="apiserver_request_total"}'
            - '--match={__name__="etcd_disk_wal_fsync_duration_seconds_bucket"}'
            - '--match={__name__="etcd_disk_wal_fsync_duration_seconds_count"}'
            - '--match={__name__="etcd_disk_wal_fsync_duration_seconds_sum"}'
            - '--match={__name__="etcd_disk_backend_commit_duration_seconds_bucket"}'
            - '--match={__name__="etcd_disk_backend_commit_duration_seconds_count"}'
            - '--match={__name__="etcd_disk_backend_commit_duration_seconds_sum"}'
            - '--match={__name__="kube_deployment_spec_replicas"}'
            - '--match={__name__="kube_deployment_status_replicas_available"}'
            - '--match={__name__="kube_pod_container_status_restarts_total"}'
            - '--match={__name__="instance:node_cpu_utilisation:rate1m"}'
            - '--match={__name__="kube_node_role"}'
            - '--match={__name__="instance:node_memory_utilisation:ratio"}'
            - '--match={__name__="expiryTime"}'
            - '--match={__name__="artifactory_http_code"}'
            - '--match={__name__="cluster_operator_conditions"}'
            - '--match={__name__="kubelet_volume_stats_available_bytes"}'
            - '--match={__name__="kubelet_volume_stats_capacity_bytes"}'
            - '--match={__name__="es_cluster_status"}'
            - '--match={__name__="es_fs_path_available_bytes"}'
            - '--match={__name__="es_fs_path_total_bytes"}'
            - '--match={__name__="kube_node_labels"}'
            - '--match={__name__="kube_node_status_allocatable_memory_bytes"}'
            - '--match={__name__="container_memory_working_set_bytes"}'
            - '--match={__name__="fluentd_output_status_retry_count"}'
            - '--match={__name__="fluentd_output_status_num_errors"}'
            - '--match={__name__="kube_pod_container_resource_requests_memory_bytes"}'
            - '--match={__name__="kube_pod_container_resource_limits_memory_bytes"}'
            - '--match={__name__="kube_node_status_allocatable_cpu_cores"}'
            - '--match={__name__="container_cpu_usage_seconds_total"}'
            - '--match={__name__="kube_pod_container_resource_requests_cpu_cores"}'
            - '--match={__name__="kube_pod_container_resource_limits_cpu_cores"}'
          env:
            - name: FROM
              value: 'http://localhost:9090'
            - name: TO
              value: >-
                https://observatorium-api-open-cluster-management-observability.shared-tools-int.maint5.eu-central-1.aws.openpaas-maint.axa-cloud.com/api/metrics/v1/default/api/v1/receive
            - name: ID
              value: demo-1
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: observability-managed-cluster-certs
              mountPath: /tlscerts
            - name: serving-certs-ca-bundle
              mountPath: /etc/serving-certs-ca-bundle
          terminationMessagePolicy: File
          image: >-
            registry.redhat.io/rhacm2/metrics-collector-rhel8@sha256:381fa8c974b3118c7115646bc2e6ecd6eec24ee616b17e0c78aaab9585bfaa87
      serviceAccount: endpoint-observability-operator-sa
      volumes:
        - name: observability-managed-cluster-certs
          secret:
            secretName: observability-managed-cluster-certs
            defaultMode: 420
        - name: serving-certs-ca-bundle
          configMap:
            name: metrics-collector-serving-certs-ca-bundle
            defaultMode: 420
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
